import Head from 'next/head'
import styles from '../styles/Prijava.module.css'
import Link from 'next/link'
//sfc

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Log in</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Log in strana */}

      <main className={styles.main}>
        <h1 className={styles.title}>
          Dobrodošli na <span className={styles.blue}>Log-in</span>
        </h1>

        <p className={styles.description}>
          Stranu za prijavljivanje
        </p>
        {/* Log-in formna */}
        <form action="">
        <Link href='./maketa'><button type='submit'>Nastavi</button></Link>
          <Link href="./register" className={styles.little}>u koliko nemate nalog</Link>
        </form>
      </main>

      {/* Futer */}
      <footer className={styles.footer}>
        <p>
          sva prava zadržava <span className={styles.blue}>orka</span>
        </p>
      </footer>
    </div>
  )
}
