import Head from 'next/head'
import styles from '../styles/Prijava.module.css'
import Link from 'next/link'



import { FirebaseApp } from '../firebase-config';
import { getAuth, signInWithPopup, GoogleAuthProvider} from 'firebase/auth'
import { useRouter } from 'next/router';
import { userAccessToken } from '../utils/fetchUserDetails';




export default function Home() {

  const firebaseAuth = getAuth(FirebaseApp);
  const provider = new GoogleAuthProvider();
  const router = useRouter();

  const signIn = () =>{
    if(localStorage.getItem('accsessToken')){
      router.push('/profile');
    }else{
      signInWithPopup(firebaseAuth, provider).then(({user}) => {
        const { refreshToken, providerData } = user;
      
        localStorage.setItem('user', JSON.stringify(providerData));
        localStorage.setItem('accsessToken', JSON.stringify(refreshToken));
  
        router.push('profile');
      }).catch(e => console.log(e));
    }
    
  };


  return (
    <div className={styles.container}>
      <Head>
        <title>Log in</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Log in strana */}

      <main className={styles.main}>
        <h1 className={styles.title}>
          Dobrodošli na <span className={styles.blue}>Vežbe</span>
        </h1>

        <p className={styles.description}>
          Stranu za prijavljivanje
        </p>
        {/* Log-in formna */}
        <div className='form'>
        <button onClick={signIn} type='button' className='button'>Nastavi</button>
          <p className={styles.little}>čak i ako nemate nalog</p>
        </div>
      </main>

      {/* Futer */}
      <footer className={styles.footer}>
        <p>
          powered by <span className={styles.blue}>orka</span>
        </p>
      </footer>
    </div>
  )
}
