import Head from 'next/head'
import styles from '../styles/Prijava.module.css'
import Link from 'next/link'

const Register = () => {
    return (
    <div className={styles.container}>
        <Head>
            <title>Register</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

      {/* Log in strana */}

      <main className={styles.main}>
        <h1 className={styles.title}>
          Dobrodošli na <span className={styles.blue}>Vežbe</span>
        </h1>

        <p className={styles.description}>
          Stranu za kreiranje naloga
        </p>
        {/* Log-in formna */}
        <form action="">
          <div className={styles.rules}>
            <p>-svaka aktivnost na sajtu će biti praćena</p>
            <p>-vaš mail i šifru će videti samo administratori</p>
            <p className='bold'>-u koliko se slažete sa uslovima korišćenja pritisnite dugme nastavi</p>
          </div>
          <Link href='./maketa'><button type='submit'>Nastavi</button></Link>
          <Link href="/" className={styles.little}>u koliko već imate nalog</Link>
        </form>
      </main>

      {/* Futer */}
      <footer className={styles.footer}>
        <p>
          powered by <span className={styles.blue}>orka</span>
        </p>
      </footer>
    </div>
    );
}
 
export default Register;